# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from myLabel import myLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnSheppCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnSheppCreate.setCheckable(False)
        self.btnSheppCreate.setFlat(True)
        self.btnSheppCreate.setObjectName("btnSheppCreate")
        self.horizontalLayout_13.addWidget(self.btnSheppCreate)
        self.comboSheppSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboSheppSize.setObjectName("comboSheppSize")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.horizontalLayout_13.addWidget(self.comboSheppSize)
        self.horizontalLayout.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowse.sizePolicy().hasHeightForWidth())
        self.btnBrowse.setSizePolicy(sizePolicy)
        self.btnBrowse.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.phantomlbl = myLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantomlbl.sizePolicy().hasHeightForWidth())
        self.phantomlbl.setSizePolicy(sizePolicy)
        self.phantomlbl.setMouseTracking(True)
        self.phantomlbl.setFrameShape(QtWidgets.QFrame.Box)
        self.phantomlbl.setText("")
        self.phantomlbl.setObjectName("phantomlbl")
        self.horizontalLayout_14.addWidget(self.phantomlbl)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGraph = QtWidgets.QWidget()
        self.tabGraph.setObjectName("tabGraph")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabGraph)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsPlotT1 = PlotWidget(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT1.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT1.setSizePolicy(sizePolicy)
        self.graphicsPlotT1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT1.setObjectName("graphicsPlotT1")
        self.verticalLayout_6.addWidget(self.graphicsPlotT1)
        self.graphicsPlotT2 = PlotWidget(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT2.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT2.setSizePolicy(sizePolicy)
        self.graphicsPlotT2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT2.setObjectName("graphicsPlotT2")
        self.verticalLayout_6.addWidget(self.graphicsPlotT2)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tabGraph, "")
        self.tabKspace = QtWidgets.QWidget()
        self.tabKspace.setObjectName("tabKspace")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabKspace)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kspaceLbl = QtWidgets.QLabel(self.tabKspace)
        self.kspaceLbl.setMinimumSize(QtCore.QSize(128, 128))
        self.kspaceLbl.setMouseTracking(True)
        self.kspaceLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.kspaceLbl.setText("")
        self.kspaceLbl.setObjectName("kspaceLbl")
        self.verticalLayout.addWidget(self.kspaceLbl)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.startSeq = QtWidgets.QPushButton(self.tabKspace)
        self.startSeq.setObjectName("startSeq")
        self.verticalLayout_4.addWidget(self.startSeq)
        self.tabWidget.addTab(self.tabKspace, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicalrepbtn = QtWidgets.QPushButton(self.tab)
        self.graphicalrepbtn.setObjectName("graphicalrepbtn")
        self.gridLayout.addWidget(self.graphicalrepbtn, 3, 0, 1, 1)
        self.clearbtn = QtWidgets.QPushButton(self.tab)
        self.clearbtn.setObjectName("clearbtn")
        self.gridLayout.addWidget(self.clearbtn, 3, 1, 1, 1)
        self.graphicsView = PlotWidget(self.tab)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 2, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 6, 2, 1, 1)
        self.graphicsView_2 = PlotWidget(self.tab_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_3.addWidget(self.graphicsView_2, 8, 0, 1, 3)
        self.t1lbl = QtWidgets.QLabel(self.tab_2)
        self.t1lbl.setText("")
        self.t1lbl.setObjectName("t1lbl")
        self.gridLayout_3.addWidget(self.t1lbl, 11, 1, 1, 1)
        self.startupText = QtWidgets.QTextEdit(self.tab_2)
        self.startupText.setMaximumSize(QtCore.QSize(100, 50))
        self.startupText.setObjectName("startupText")
        self.gridLayout_3.addWidget(self.startupText, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 11, 0, 1, 1)
        self.artifact1btn = QtWidgets.QPushButton(self.tab_2)
        self.artifact1btn.setObjectName("artifact1btn")
        self.gridLayout_3.addWidget(self.artifact1btn, 1, 2, 1, 1)
        self.artifact2btn = QtWidgets.QPushButton(self.tab_2)
        self.artifact2btn.setObjectName("artifact2btn")
        self.gridLayout_3.addWidget(self.artifact2btn, 2, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sebtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.sebtn.setObjectName("sebtn")
        self.gridLayout_4.addWidget(self.sebtn, 2, 0, 1, 1)
        self.grebtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.grebtn.setObjectName("grebtn")
        self.gridLayout_4.addWidget(self.grebtn, 0, 0, 1, 1)
        self.ssfpbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.ssfpbtn.setObjectName("ssfpbtn")
        self.gridLayout_4.addWidget(self.ssfpbtn, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 5, 0, 3, 1)
        self.prepText = QtWidgets.QTextEdit(self.tab_2)
        self.prepText.setMaximumSize(QtCore.QSize(100, 50))
        self.prepText.setObjectName("prepText")
        self.gridLayout_3.addWidget(self.prepText, 4, 2, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox.setObjectName("groupBox")
        self.T2prepbtn = QtWidgets.QRadioButton(self.groupBox)
        self.T2prepbtn.setGeometry(QtCore.QRect(10, 20, 117, 22))
        self.T2prepbtn.setObjectName("T2prepbtn")
        self.taggingbtn = QtWidgets.QRadioButton(self.groupBox)
        self.taggingbtn.setGeometry(QtCore.QRect(10, 50, 117, 22))
        self.taggingbtn.setObjectName("taggingbtn")
        self.irbtn = QtWidgets.QRadioButton(self.groupBox)
        self.irbtn.setGeometry(QtCore.QRect(10, 80, 117, 22))
        self.irbtn.setObjectName("irbtn")
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 5, 2)
        self.preplbl = QtWidgets.QLabel(self.tab_2)
        self.preplbl.setObjectName("preplbl")
        self.gridLayout_3.addWidget(self.preplbl, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_14.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12, 0, QtCore.Qt.AlignRight)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.comboViewMode = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboViewMode.sizePolicy().hasHeightForWidth())
        self.comboViewMode.setSizePolicy(sizePolicy)
        self.comboViewMode.setObjectName("comboViewMode")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.horizontalLayout_15.addWidget(self.comboViewMode)
        spacerItem4 = QtWidgets.QSpacerItem(90, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13, 0, QtCore.Qt.AlignRight)
        self.TimeEcho = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeEcho.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeEcho.setObjectName("TimeEcho")
        self.horizontalLayout_15.addWidget(self.TimeEcho)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14, 0, QtCore.Qt.AlignRight)
        self.TimeRepeat = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeRepeat.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeRepeat.setObjectName("TimeRepeat")
        self.horizontalLayout_15.addWidget(self.TimeRepeat)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15, 0, QtCore.Qt.AlignRight)
        self.FlipAngle = QtWidgets.QLineEdit(self.centralwidget)
        self.FlipAngle.setMaximumSize(QtCore.QSize(40, 15))
        self.FlipAngle.setObjectName("FlipAngle")
        self.horizontalLayout_15.addWidget(self.FlipAngle)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInversion = QtWidgets.QAction(MainWindow)
        self.actionInversion.setObjectName("actionInversion")
        self.actionSpin_e = QtWidgets.QAction(MainWindow)
        self.actionSpin_e.setObjectName("actionSpin_e")
        self.actionTagging = QtWidgets.QAction(MainWindow)
        self.actionTagging.setObjectName("actionTagging")
        self.actionGRE = QtWidgets.QAction(MainWindow)
        self.actionGRE.setObjectName("actionGRE")
        self.actionSSFP = QtWidgets.QAction(MainWindow)
        self.actionSSFP.setObjectName("actionSSFP")
        self.actionSpin_Echo = QtWidgets.QAction(MainWindow)
        self.actionSpin_Echo.setObjectName("actionSpin_Echo")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI Sequence Simulator"))
        self.btnSheppCreate.setText(_translate("MainWindow", "Shepp-Logan"))
        self.comboSheppSize.setItemText(0, _translate("MainWindow", "32"))
        self.comboSheppSize.setItemText(1, _translate("MainWindow", "64"))
        self.comboSheppSize.setItemText(2, _translate("MainWindow", "128"))
        self.comboSheppSize.setItemText(3, _translate("MainWindow", "256"))
        self.comboSheppSize.setItemText(4, _translate("MainWindow", "512"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraph), _translate("MainWindow", "Graphs"))
        self.startSeq.setText(_translate("MainWindow", "Start Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKspace), _translate("MainWindow", "K-space "))
        self.graphicalrepbtn.setText(_translate("MainWindow", "show"))
        self.clearbtn.setText(_translate("MainWindow", "clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Graphical Representaion"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Start up cycle</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">T1 value :</p></body></html>"))
        self.artifact1btn.setText(_translate("MainWindow", "Artifact 1"))
        self.artifact2btn.setText(_translate("MainWindow", "Artifact 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Acquisition"))
        self.sebtn.setText(_translate("MainWindow", "Spin echo"))
        self.grebtn.setText(_translate("MainWindow", "GRE"))
        self.ssfpbtn.setText(_translate("MainWindow", "SSFP"))
        self.groupBox.setTitle(_translate("MainWindow", "Preparation"))
        self.T2prepbtn.setText(_translate("MainWindow", "T2 prep"))
        self.taggingbtn.setText(_translate("MainWindow", "Tagging"))
        self.irbtn.setText(_translate("MainWindow", "IR"))
        self.preplbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Options"))
        self.label_12.setText(_translate("MainWindow", "Show"))
        self.comboViewMode.setItemText(0, _translate("MainWindow", "PD"))
        self.comboViewMode.setItemText(1, _translate("MainWindow", "T1"))
        self.comboViewMode.setItemText(2, _translate("MainWindow", "T2"))
        self.label_13.setText(_translate("MainWindow", "TE"))
        self.label_14.setText(_translate("MainWindow", "TR"))
        self.label_15.setText(_translate("MainWindow", "FA"))
        self.actionInversion.setText(_translate("MainWindow", "Inversion (T1)"))
        self.actionSpin_e.setText(_translate("MainWindow", "T2"))
        self.actionTagging.setText(_translate("MainWindow", "Tagging "))
        self.actionGRE.setText(_translate("MainWindow", "GRE"))
        self.actionSSFP.setText(_translate("MainWindow", "SSFP"))
        self.actionSpin_Echo.setText(_translate("MainWindow", "Spin Echo"))

from pyqtgraph import PlotWidget
